version: '3'

services:
  fundlyup.com:
    container_name: fundlyup.com
    image: nginx
    ports:
    - 8080:8080
    volumes:
    - ./docker/nginx/front.conf:/etc/nginx/conf.d/front.conf
    - .:/app
    networks:
    - fundlyup-network

  tests:
    container_name: nightwatch
    build:
      context: .
    depends_on:
    - hub
    - fundlyup.com
    volumes:
    - .:/app:rw
    command: sh -c 'yarn && yarn build && yarn lint && yarn tests'
    networks:
    - fundlyup-network

  hub:
    container_name: hub
    image: selenium/hub
    environment:
      GRID_BROWSER_TIMEOUT: 120000
      GRID_TIMEOUT: 120000
      GRID_MAX_SESSION: 100
      GRID_NEW_SESSION_WAIT_TIMEOUT: 300000
    ports:
    - 4444:4444
    networks:
    - fundlyup-network

  chrome:
    image: selenium/node-chrome
    depends_on:
    - hub
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    networks:
    - fundlyup-network

  firefox:
    image: selenium/node-firefox
    depends_on:
    - hub
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    networks:
    - fundlyup-network

networks:
  fundlyup-network:
    driver: bridge
